/*
Nuki API

The Nuki Web Api

API version: 3.10.1
Contact: contact@nuki.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddressUnit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddressUnit{}

// AddressUnit struct for AddressUnit
type AddressUnit struct {
	// The id
	Id *string `json:"id,omitempty"`
	// The name of the address unit
	Name string `json:"name"`
	// The address id
	AddressId *int32 `json:"addressId,omitempty"`
	// The address token id
	AddressTokenId *string `json:"addressTokenId,omitempty"`
	// The operation id - if set it's locked for another operation
	OperationId *string `json:"operationId,omitempty"`
}

type _AddressUnit AddressUnit

// NewAddressUnit instantiates a new AddressUnit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddressUnit(name string) *AddressUnit {
	this := AddressUnit{}
	this.Name = name
	return &this
}

// NewAddressUnitWithDefaults instantiates a new AddressUnit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddressUnitWithDefaults() *AddressUnit {
	this := AddressUnit{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AddressUnit) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressUnit) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AddressUnit) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AddressUnit) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value
func (o *AddressUnit) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AddressUnit) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AddressUnit) SetName(v string) {
	o.Name = v
}

// GetAddressId returns the AddressId field value if set, zero value otherwise.
func (o *AddressUnit) GetAddressId() int32 {
	if o == nil || IsNil(o.AddressId) {
		var ret int32
		return ret
	}
	return *o.AddressId
}

// GetAddressIdOk returns a tuple with the AddressId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressUnit) GetAddressIdOk() (*int32, bool) {
	if o == nil || IsNil(o.AddressId) {
		return nil, false
	}
	return o.AddressId, true
}

// HasAddressId returns a boolean if a field has been set.
func (o *AddressUnit) HasAddressId() bool {
	if o != nil && !IsNil(o.AddressId) {
		return true
	}

	return false
}

// SetAddressId gets a reference to the given int32 and assigns it to the AddressId field.
func (o *AddressUnit) SetAddressId(v int32) {
	o.AddressId = &v
}

// GetAddressTokenId returns the AddressTokenId field value if set, zero value otherwise.
func (o *AddressUnit) GetAddressTokenId() string {
	if o == nil || IsNil(o.AddressTokenId) {
		var ret string
		return ret
	}
	return *o.AddressTokenId
}

// GetAddressTokenIdOk returns a tuple with the AddressTokenId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressUnit) GetAddressTokenIdOk() (*string, bool) {
	if o == nil || IsNil(o.AddressTokenId) {
		return nil, false
	}
	return o.AddressTokenId, true
}

// HasAddressTokenId returns a boolean if a field has been set.
func (o *AddressUnit) HasAddressTokenId() bool {
	if o != nil && !IsNil(o.AddressTokenId) {
		return true
	}

	return false
}

// SetAddressTokenId gets a reference to the given string and assigns it to the AddressTokenId field.
func (o *AddressUnit) SetAddressTokenId(v string) {
	o.AddressTokenId = &v
}

// GetOperationId returns the OperationId field value if set, zero value otherwise.
func (o *AddressUnit) GetOperationId() string {
	if o == nil || IsNil(o.OperationId) {
		var ret string
		return ret
	}
	return *o.OperationId
}

// GetOperationIdOk returns a tuple with the OperationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressUnit) GetOperationIdOk() (*string, bool) {
	if o == nil || IsNil(o.OperationId) {
		return nil, false
	}
	return o.OperationId, true
}

// HasOperationId returns a boolean if a field has been set.
func (o *AddressUnit) HasOperationId() bool {
	if o != nil && !IsNil(o.OperationId) {
		return true
	}

	return false
}

// SetOperationId gets a reference to the given string and assigns it to the OperationId field.
func (o *AddressUnit) SetOperationId(v string) {
	o.OperationId = &v
}

func (o AddressUnit) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddressUnit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.AddressId) {
		toSerialize["addressId"] = o.AddressId
	}
	if !IsNil(o.AddressTokenId) {
		toSerialize["addressTokenId"] = o.AddressTokenId
	}
	if !IsNil(o.OperationId) {
		toSerialize["operationId"] = o.OperationId
	}
	return toSerialize, nil
}

func (o *AddressUnit) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddressUnit := _AddressUnit{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddressUnit)

	if err != nil {
		return err
	}

	*o = AddressUnit(varAddressUnit)

	return err
}

type NullableAddressUnit struct {
	value *AddressUnit
	isSet bool
}

func (v NullableAddressUnit) Get() *AddressUnit {
	return v.value
}

func (v *NullableAddressUnit) Set(val *AddressUnit) {
	v.value = val
	v.isSet = true
}

func (v NullableAddressUnit) IsSet() bool {
	return v.isSet
}

func (v *NullableAddressUnit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddressUnit(val *AddressUnit) *NullableAddressUnit {
	return &NullableAddressUnit{value: val, isSet: true}
}

func (v NullableAddressUnit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddressUnit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


