/*
Nuki API

The Nuki Web Api

API version: 3.13.0
Contact: contact@nuki.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AdvancedApiKeyCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdvancedApiKeyCreate{}

// AdvancedApiKeyCreate struct for AdvancedApiKeyCreate
type AdvancedApiKeyCreate struct {
	// The name of the company for which you apply for access
	Name string `json:"name"`
	// The country of the headquarter or the country where you are mainly doing business in
	Country string `json:"country"`
	// Describe the services and/or products you offer to your customers and how your customers would use Nuki devices in their processes
	Description string `json:"description"`
	// The application type
	Type string `json:"type"`
	// The status of the webhook posting automation
	WebhookStatus *string `json:"webhookStatus,omitempty"`
	// A website where we can find more information on the company and its business model
	Url string `json:"url"`
	// An email address where we can contact you for checks on your application
	Email string `json:"email"`
	// The URL where our webhooks should point to
	WebhookUrl string `json:"webhookUrl"`
	// The features to trigger webhooks, for all types except 'ONLY_SECRET'
	WebhookFeatures []string `json:"webhookFeatures"`
	// Whether the advanced API key is restricted
	Restricted bool `json:"restricted"`
}

type _AdvancedApiKeyCreate AdvancedApiKeyCreate

// NewAdvancedApiKeyCreate instantiates a new AdvancedApiKeyCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvancedApiKeyCreate(name string, country string, description string, type_ string, url string, email string, webhookUrl string, webhookFeatures []string, restricted bool) *AdvancedApiKeyCreate {
	this := AdvancedApiKeyCreate{}
	this.Name = name
	this.Country = country
	this.Description = description
	this.Type = type_
	this.Url = url
	this.Email = email
	this.WebhookUrl = webhookUrl
	this.WebhookFeatures = webhookFeatures
	this.Restricted = restricted
	return &this
}

// NewAdvancedApiKeyCreateWithDefaults instantiates a new AdvancedApiKeyCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvancedApiKeyCreateWithDefaults() *AdvancedApiKeyCreate {
	this := AdvancedApiKeyCreate{}
	return &this
}

// GetName returns the Name field value
func (o *AdvancedApiKeyCreate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKeyCreate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AdvancedApiKeyCreate) SetName(v string) {
	o.Name = v
}

// GetCountry returns the Country field value
func (o *AdvancedApiKeyCreate) GetCountry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Country
}

// GetCountryOk returns a tuple with the Country field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKeyCreate) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Country, true
}

// SetCountry sets field value
func (o *AdvancedApiKeyCreate) SetCountry(v string) {
	o.Country = v
}

// GetDescription returns the Description field value
func (o *AdvancedApiKeyCreate) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKeyCreate) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *AdvancedApiKeyCreate) SetDescription(v string) {
	o.Description = v
}

// GetType returns the Type field value
func (o *AdvancedApiKeyCreate) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKeyCreate) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AdvancedApiKeyCreate) SetType(v string) {
	o.Type = v
}

// GetWebhookStatus returns the WebhookStatus field value if set, zero value otherwise.
func (o *AdvancedApiKeyCreate) GetWebhookStatus() string {
	if o == nil || IsNil(o.WebhookStatus) {
		var ret string
		return ret
	}
	return *o.WebhookStatus
}

// GetWebhookStatusOk returns a tuple with the WebhookStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedApiKeyCreate) GetWebhookStatusOk() (*string, bool) {
	if o == nil || IsNil(o.WebhookStatus) {
		return nil, false
	}
	return o.WebhookStatus, true
}

// HasWebhookStatus returns a boolean if a field has been set.
func (o *AdvancedApiKeyCreate) HasWebhookStatus() bool {
	if o != nil && !IsNil(o.WebhookStatus) {
		return true
	}

	return false
}

// SetWebhookStatus gets a reference to the given string and assigns it to the WebhookStatus field.
func (o *AdvancedApiKeyCreate) SetWebhookStatus(v string) {
	o.WebhookStatus = &v
}

// GetUrl returns the Url field value
func (o *AdvancedApiKeyCreate) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKeyCreate) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *AdvancedApiKeyCreate) SetUrl(v string) {
	o.Url = v
}

// GetEmail returns the Email field value
func (o *AdvancedApiKeyCreate) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKeyCreate) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *AdvancedApiKeyCreate) SetEmail(v string) {
	o.Email = v
}

// GetWebhookUrl returns the WebhookUrl field value
func (o *AdvancedApiKeyCreate) GetWebhookUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WebhookUrl
}

// GetWebhookUrlOk returns a tuple with the WebhookUrl field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKeyCreate) GetWebhookUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WebhookUrl, true
}

// SetWebhookUrl sets field value
func (o *AdvancedApiKeyCreate) SetWebhookUrl(v string) {
	o.WebhookUrl = v
}

// GetWebhookFeatures returns the WebhookFeatures field value
func (o *AdvancedApiKeyCreate) GetWebhookFeatures() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.WebhookFeatures
}

// GetWebhookFeaturesOk returns a tuple with the WebhookFeatures field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKeyCreate) GetWebhookFeaturesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WebhookFeatures, true
}

// SetWebhookFeatures sets field value
func (o *AdvancedApiKeyCreate) SetWebhookFeatures(v []string) {
	o.WebhookFeatures = v
}

// GetRestricted returns the Restricted field value
func (o *AdvancedApiKeyCreate) GetRestricted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Restricted
}

// GetRestrictedOk returns a tuple with the Restricted field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKeyCreate) GetRestrictedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Restricted, true
}

// SetRestricted sets field value
func (o *AdvancedApiKeyCreate) SetRestricted(v bool) {
	o.Restricted = v
}

func (o AdvancedApiKeyCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdvancedApiKeyCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["country"] = o.Country
	toSerialize["description"] = o.Description
	toSerialize["type"] = o.Type
	if !IsNil(o.WebhookStatus) {
		toSerialize["webhookStatus"] = o.WebhookStatus
	}
	toSerialize["url"] = o.Url
	toSerialize["email"] = o.Email
	toSerialize["webhookUrl"] = o.WebhookUrl
	toSerialize["webhookFeatures"] = o.WebhookFeatures
	toSerialize["restricted"] = o.Restricted
	return toSerialize, nil
}

func (o *AdvancedApiKeyCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"country",
		"description",
		"type",
		"url",
		"email",
		"webhookUrl",
		"webhookFeatures",
		"restricted",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdvancedApiKeyCreate := _AdvancedApiKeyCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdvancedApiKeyCreate)

	if err != nil {
		return err
	}

	*o = AdvancedApiKeyCreate(varAdvancedApiKeyCreate)

	return err
}

type NullableAdvancedApiKeyCreate struct {
	value *AdvancedApiKeyCreate
	isSet bool
}

func (v NullableAdvancedApiKeyCreate) Get() *AdvancedApiKeyCreate {
	return v.value
}

func (v *NullableAdvancedApiKeyCreate) Set(val *AdvancedApiKeyCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvancedApiKeyCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvancedApiKeyCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvancedApiKeyCreate(val *AdvancedApiKeyCreate) *NullableAdvancedApiKeyCreate {
	return &NullableAdvancedApiKeyCreate{value: val, isSet: true}
}

func (v NullableAdvancedApiKeyCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvancedApiKeyCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


