/*
Nuki API

The Nuki Web Api

API version: 3.10.1
Contact: contact@nuki.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddressCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddressCreate{}

// AddressCreate struct for AddressCreate
type AddressCreate struct {
	// The name of the address
	Name string `json:"name"`
	// The smartlocks for this address
	SmartlockIds []int64 `json:"smartlockIds"`
}

type _AddressCreate AddressCreate

// NewAddressCreate instantiates a new AddressCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddressCreate(name string, smartlockIds []int64) *AddressCreate {
	this := AddressCreate{}
	this.Name = name
	this.SmartlockIds = smartlockIds
	return &this
}

// NewAddressCreateWithDefaults instantiates a new AddressCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddressCreateWithDefaults() *AddressCreate {
	this := AddressCreate{}
	return &this
}

// GetName returns the Name field value
func (o *AddressCreate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AddressCreate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AddressCreate) SetName(v string) {
	o.Name = v
}

// GetSmartlockIds returns the SmartlockIds field value
func (o *AddressCreate) GetSmartlockIds() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}

	return o.SmartlockIds
}

// GetSmartlockIdsOk returns a tuple with the SmartlockIds field value
// and a boolean to check if the value has been set.
func (o *AddressCreate) GetSmartlockIdsOk() ([]int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.SmartlockIds, true
}

// SetSmartlockIds sets field value
func (o *AddressCreate) SetSmartlockIds(v []int64) {
	o.SmartlockIds = v
}

func (o AddressCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddressCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["smartlockIds"] = o.SmartlockIds
	return toSerialize, nil
}

func (o *AddressCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"smartlockIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddressCreate := _AddressCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddressCreate)

	if err != nil {
		return err
	}

	*o = AddressCreate(varAddressCreate)

	return err
}

type NullableAddressCreate struct {
	value *AddressCreate
	isSet bool
}

func (v NullableAddressCreate) Get() *AddressCreate {
	return v.value
}

func (v *NullableAddressCreate) Set(val *AddressCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableAddressCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableAddressCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddressCreate(val *AddressCreate) *NullableAddressCreate {
	return &NullableAddressCreate{value: val, isSet: true}
}

func (v NullableAddressCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddressCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


