/*
Nuki API

The Nuki Web Api

API version: 3.8.1
Contact: contact@nuki.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ReservationAccessTimesUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReservationAccessTimesUpdate{}

// ReservationAccessTimesUpdate struct for ReservationAccessTimesUpdate
type ReservationAccessTimesUpdate struct {
	// Custom check in time in minutes from midnight
	CheckInTime *int32 `json:"checkInTime,omitempty"`
	// Custom check out time in minutes from midnight
	CheckOutTime *int32 `json:"checkOutTime,omitempty"`
}

// NewReservationAccessTimesUpdate instantiates a new ReservationAccessTimesUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReservationAccessTimesUpdate() *ReservationAccessTimesUpdate {
	this := ReservationAccessTimesUpdate{}
	return &this
}

// NewReservationAccessTimesUpdateWithDefaults instantiates a new ReservationAccessTimesUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReservationAccessTimesUpdateWithDefaults() *ReservationAccessTimesUpdate {
	this := ReservationAccessTimesUpdate{}
	return &this
}

// GetCheckInTime returns the CheckInTime field value if set, zero value otherwise.
func (o *ReservationAccessTimesUpdate) GetCheckInTime() int32 {
	if o == nil || IsNil(o.CheckInTime) {
		var ret int32
		return ret
	}
	return *o.CheckInTime
}

// GetCheckInTimeOk returns a tuple with the CheckInTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReservationAccessTimesUpdate) GetCheckInTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.CheckInTime) {
		return nil, false
	}
	return o.CheckInTime, true
}

// HasCheckInTime returns a boolean if a field has been set.
func (o *ReservationAccessTimesUpdate) HasCheckInTime() bool {
	if o != nil && !IsNil(o.CheckInTime) {
		return true
	}

	return false
}

// SetCheckInTime gets a reference to the given int32 and assigns it to the CheckInTime field.
func (o *ReservationAccessTimesUpdate) SetCheckInTime(v int32) {
	o.CheckInTime = &v
}

// GetCheckOutTime returns the CheckOutTime field value if set, zero value otherwise.
func (o *ReservationAccessTimesUpdate) GetCheckOutTime() int32 {
	if o == nil || IsNil(o.CheckOutTime) {
		var ret int32
		return ret
	}
	return *o.CheckOutTime
}

// GetCheckOutTimeOk returns a tuple with the CheckOutTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReservationAccessTimesUpdate) GetCheckOutTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.CheckOutTime) {
		return nil, false
	}
	return o.CheckOutTime, true
}

// HasCheckOutTime returns a boolean if a field has been set.
func (o *ReservationAccessTimesUpdate) HasCheckOutTime() bool {
	if o != nil && !IsNil(o.CheckOutTime) {
		return true
	}

	return false
}

// SetCheckOutTime gets a reference to the given int32 and assigns it to the CheckOutTime field.
func (o *ReservationAccessTimesUpdate) SetCheckOutTime(v int32) {
	o.CheckOutTime = &v
}

func (o ReservationAccessTimesUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReservationAccessTimesUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CheckInTime) {
		toSerialize["checkInTime"] = o.CheckInTime
	}
	if !IsNil(o.CheckOutTime) {
		toSerialize["checkOutTime"] = o.CheckOutTime
	}
	return toSerialize, nil
}

type NullableReservationAccessTimesUpdate struct {
	value *ReservationAccessTimesUpdate
	isSet bool
}

func (v NullableReservationAccessTimesUpdate) Get() *ReservationAccessTimesUpdate {
	return v.value
}

func (v *NullableReservationAccessTimesUpdate) Set(val *ReservationAccessTimesUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableReservationAccessTimesUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableReservationAccessTimesUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReservationAccessTimesUpdate(val *ReservationAccessTimesUpdate) *NullableReservationAccessTimesUpdate {
	return &NullableReservationAccessTimesUpdate{value: val, isSet: true}
}

func (v NullableReservationAccessTimesUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReservationAccessTimesUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


