/*
Nuki API

The Nuki Web Api

API version: 3.10.1
Contact: contact@nuki.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ApiKeyService type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiKeyService{}

// ApiKeyService struct for ApiKeyService
type ApiKeyService struct {
	ByActiveWebhook *CompletableFutureListApiKey `json:"byActiveWebhook,omitempty"`
}

// NewApiKeyService instantiates a new ApiKeyService object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiKeyService() *ApiKeyService {
	this := ApiKeyService{}
	return &this
}

// NewApiKeyServiceWithDefaults instantiates a new ApiKeyService object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiKeyServiceWithDefaults() *ApiKeyService {
	this := ApiKeyService{}
	return &this
}

// GetByActiveWebhook returns the ByActiveWebhook field value if set, zero value otherwise.
func (o *ApiKeyService) GetByActiveWebhook() CompletableFutureListApiKey {
	if o == nil || IsNil(o.ByActiveWebhook) {
		var ret CompletableFutureListApiKey
		return ret
	}
	return *o.ByActiveWebhook
}

// GetByActiveWebhookOk returns a tuple with the ByActiveWebhook field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiKeyService) GetByActiveWebhookOk() (*CompletableFutureListApiKey, bool) {
	if o == nil || IsNil(o.ByActiveWebhook) {
		return nil, false
	}
	return o.ByActiveWebhook, true
}

// HasByActiveWebhook returns a boolean if a field has been set.
func (o *ApiKeyService) HasByActiveWebhook() bool {
	if o != nil && !IsNil(o.ByActiveWebhook) {
		return true
	}

	return false
}

// SetByActiveWebhook gets a reference to the given CompletableFutureListApiKey and assigns it to the ByActiveWebhook field.
func (o *ApiKeyService) SetByActiveWebhook(v CompletableFutureListApiKey) {
	o.ByActiveWebhook = &v
}

func (o ApiKeyService) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiKeyService) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ByActiveWebhook) {
		toSerialize["byActiveWebhook"] = o.ByActiveWebhook
	}
	return toSerialize, nil
}

type NullableApiKeyService struct {
	value *ApiKeyService
	isSet bool
}

func (v NullableApiKeyService) Get() *ApiKeyService {
	return v.value
}

func (v *NullableApiKeyService) Set(val *ApiKeyService) {
	v.value = val
	v.isSet = true
}

func (v NullableApiKeyService) IsSet() bool {
	return v.isSet
}

func (v *NullableApiKeyService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiKeyService(val *ApiKeyService) *NullableApiKeyService {
	return &NullableApiKeyService{value: val, isSet: true}
}

func (v NullableApiKeyService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiKeyService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


