/*
Nuki API

The Nuki Web Api

API version: 3.10.1
Contact: contact@nuki.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the SmartlockAuthWithSharedKeyCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SmartlockAuthWithSharedKeyCreate{}

// SmartlockAuthWithSharedKeyCreate struct for SmartlockAuthWithSharedKeyCreate
type SmartlockAuthWithSharedKeyCreate struct {
	// The name of the authorization (max 32 chars)
	Name string `json:"name"`
	// The allowed from date
	AllowedFromDate *time.Time `json:"allowedFromDate,omitempty"`
	// The allowed until date
	AllowedUntilDate *time.Time `json:"allowedUntilDate,omitempty"`
	// The allowed weekdays bitmask: 64 .. monday, 32 .. tuesday, 16 .. wednesday, 8 .. thursday, 4 .. friday, 2 .. saturday, 1 .. sunday
	AllowedWeekDays *int32 `json:"allowedWeekDays,omitempty"`
	// The allowed from time (in minutes from midnight)
	AllowedFromTime *int32 `json:"allowedFromTime,omitempty"`
	// The allowed until time (in minutes from midnight)
	AllowedUntilTime *int32 `json:"allowedUntilTime,omitempty"`
	// The id of the linked account user
	AccountUserId *int32 `json:"accountUserId,omitempty"`
}

type _SmartlockAuthWithSharedKeyCreate SmartlockAuthWithSharedKeyCreate

// NewSmartlockAuthWithSharedKeyCreate instantiates a new SmartlockAuthWithSharedKeyCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSmartlockAuthWithSharedKeyCreate(name string) *SmartlockAuthWithSharedKeyCreate {
	this := SmartlockAuthWithSharedKeyCreate{}
	this.Name = name
	return &this
}

// NewSmartlockAuthWithSharedKeyCreateWithDefaults instantiates a new SmartlockAuthWithSharedKeyCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSmartlockAuthWithSharedKeyCreateWithDefaults() *SmartlockAuthWithSharedKeyCreate {
	this := SmartlockAuthWithSharedKeyCreate{}
	return &this
}

// GetName returns the Name field value
func (o *SmartlockAuthWithSharedKeyCreate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SmartlockAuthWithSharedKeyCreate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SmartlockAuthWithSharedKeyCreate) SetName(v string) {
	o.Name = v
}

// GetAllowedFromDate returns the AllowedFromDate field value if set, zero value otherwise.
func (o *SmartlockAuthWithSharedKeyCreate) GetAllowedFromDate() time.Time {
	if o == nil || IsNil(o.AllowedFromDate) {
		var ret time.Time
		return ret
	}
	return *o.AllowedFromDate
}

// GetAllowedFromDateOk returns a tuple with the AllowedFromDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartlockAuthWithSharedKeyCreate) GetAllowedFromDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.AllowedFromDate) {
		return nil, false
	}
	return o.AllowedFromDate, true
}

// HasAllowedFromDate returns a boolean if a field has been set.
func (o *SmartlockAuthWithSharedKeyCreate) HasAllowedFromDate() bool {
	if o != nil && !IsNil(o.AllowedFromDate) {
		return true
	}

	return false
}

// SetAllowedFromDate gets a reference to the given time.Time and assigns it to the AllowedFromDate field.
func (o *SmartlockAuthWithSharedKeyCreate) SetAllowedFromDate(v time.Time) {
	o.AllowedFromDate = &v
}

// GetAllowedUntilDate returns the AllowedUntilDate field value if set, zero value otherwise.
func (o *SmartlockAuthWithSharedKeyCreate) GetAllowedUntilDate() time.Time {
	if o == nil || IsNil(o.AllowedUntilDate) {
		var ret time.Time
		return ret
	}
	return *o.AllowedUntilDate
}

// GetAllowedUntilDateOk returns a tuple with the AllowedUntilDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartlockAuthWithSharedKeyCreate) GetAllowedUntilDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.AllowedUntilDate) {
		return nil, false
	}
	return o.AllowedUntilDate, true
}

// HasAllowedUntilDate returns a boolean if a field has been set.
func (o *SmartlockAuthWithSharedKeyCreate) HasAllowedUntilDate() bool {
	if o != nil && !IsNil(o.AllowedUntilDate) {
		return true
	}

	return false
}

// SetAllowedUntilDate gets a reference to the given time.Time and assigns it to the AllowedUntilDate field.
func (o *SmartlockAuthWithSharedKeyCreate) SetAllowedUntilDate(v time.Time) {
	o.AllowedUntilDate = &v
}

// GetAllowedWeekDays returns the AllowedWeekDays field value if set, zero value otherwise.
func (o *SmartlockAuthWithSharedKeyCreate) GetAllowedWeekDays() int32 {
	if o == nil || IsNil(o.AllowedWeekDays) {
		var ret int32
		return ret
	}
	return *o.AllowedWeekDays
}

// GetAllowedWeekDaysOk returns a tuple with the AllowedWeekDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartlockAuthWithSharedKeyCreate) GetAllowedWeekDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.AllowedWeekDays) {
		return nil, false
	}
	return o.AllowedWeekDays, true
}

// HasAllowedWeekDays returns a boolean if a field has been set.
func (o *SmartlockAuthWithSharedKeyCreate) HasAllowedWeekDays() bool {
	if o != nil && !IsNil(o.AllowedWeekDays) {
		return true
	}

	return false
}

// SetAllowedWeekDays gets a reference to the given int32 and assigns it to the AllowedWeekDays field.
func (o *SmartlockAuthWithSharedKeyCreate) SetAllowedWeekDays(v int32) {
	o.AllowedWeekDays = &v
}

// GetAllowedFromTime returns the AllowedFromTime field value if set, zero value otherwise.
func (o *SmartlockAuthWithSharedKeyCreate) GetAllowedFromTime() int32 {
	if o == nil || IsNil(o.AllowedFromTime) {
		var ret int32
		return ret
	}
	return *o.AllowedFromTime
}

// GetAllowedFromTimeOk returns a tuple with the AllowedFromTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartlockAuthWithSharedKeyCreate) GetAllowedFromTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.AllowedFromTime) {
		return nil, false
	}
	return o.AllowedFromTime, true
}

// HasAllowedFromTime returns a boolean if a field has been set.
func (o *SmartlockAuthWithSharedKeyCreate) HasAllowedFromTime() bool {
	if o != nil && !IsNil(o.AllowedFromTime) {
		return true
	}

	return false
}

// SetAllowedFromTime gets a reference to the given int32 and assigns it to the AllowedFromTime field.
func (o *SmartlockAuthWithSharedKeyCreate) SetAllowedFromTime(v int32) {
	o.AllowedFromTime = &v
}

// GetAllowedUntilTime returns the AllowedUntilTime field value if set, zero value otherwise.
func (o *SmartlockAuthWithSharedKeyCreate) GetAllowedUntilTime() int32 {
	if o == nil || IsNil(o.AllowedUntilTime) {
		var ret int32
		return ret
	}
	return *o.AllowedUntilTime
}

// GetAllowedUntilTimeOk returns a tuple with the AllowedUntilTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartlockAuthWithSharedKeyCreate) GetAllowedUntilTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.AllowedUntilTime) {
		return nil, false
	}
	return o.AllowedUntilTime, true
}

// HasAllowedUntilTime returns a boolean if a field has been set.
func (o *SmartlockAuthWithSharedKeyCreate) HasAllowedUntilTime() bool {
	if o != nil && !IsNil(o.AllowedUntilTime) {
		return true
	}

	return false
}

// SetAllowedUntilTime gets a reference to the given int32 and assigns it to the AllowedUntilTime field.
func (o *SmartlockAuthWithSharedKeyCreate) SetAllowedUntilTime(v int32) {
	o.AllowedUntilTime = &v
}

// GetAccountUserId returns the AccountUserId field value if set, zero value otherwise.
func (o *SmartlockAuthWithSharedKeyCreate) GetAccountUserId() int32 {
	if o == nil || IsNil(o.AccountUserId) {
		var ret int32
		return ret
	}
	return *o.AccountUserId
}

// GetAccountUserIdOk returns a tuple with the AccountUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartlockAuthWithSharedKeyCreate) GetAccountUserIdOk() (*int32, bool) {
	if o == nil || IsNil(o.AccountUserId) {
		return nil, false
	}
	return o.AccountUserId, true
}

// HasAccountUserId returns a boolean if a field has been set.
func (o *SmartlockAuthWithSharedKeyCreate) HasAccountUserId() bool {
	if o != nil && !IsNil(o.AccountUserId) {
		return true
	}

	return false
}

// SetAccountUserId gets a reference to the given int32 and assigns it to the AccountUserId field.
func (o *SmartlockAuthWithSharedKeyCreate) SetAccountUserId(v int32) {
	o.AccountUserId = &v
}

func (o SmartlockAuthWithSharedKeyCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SmartlockAuthWithSharedKeyCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.AllowedFromDate) {
		toSerialize["allowedFromDate"] = o.AllowedFromDate
	}
	if !IsNil(o.AllowedUntilDate) {
		toSerialize["allowedUntilDate"] = o.AllowedUntilDate
	}
	if !IsNil(o.AllowedWeekDays) {
		toSerialize["allowedWeekDays"] = o.AllowedWeekDays
	}
	if !IsNil(o.AllowedFromTime) {
		toSerialize["allowedFromTime"] = o.AllowedFromTime
	}
	if !IsNil(o.AllowedUntilTime) {
		toSerialize["allowedUntilTime"] = o.AllowedUntilTime
	}
	if !IsNil(o.AccountUserId) {
		toSerialize["accountUserId"] = o.AccountUserId
	}
	return toSerialize, nil
}

func (o *SmartlockAuthWithSharedKeyCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSmartlockAuthWithSharedKeyCreate := _SmartlockAuthWithSharedKeyCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSmartlockAuthWithSharedKeyCreate)

	if err != nil {
		return err
	}

	*o = SmartlockAuthWithSharedKeyCreate(varSmartlockAuthWithSharedKeyCreate)

	return err
}

type NullableSmartlockAuthWithSharedKeyCreate struct {
	value *SmartlockAuthWithSharedKeyCreate
	isSet bool
}

func (v NullableSmartlockAuthWithSharedKeyCreate) Get() *SmartlockAuthWithSharedKeyCreate {
	return v.value
}

func (v *NullableSmartlockAuthWithSharedKeyCreate) Set(val *SmartlockAuthWithSharedKeyCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableSmartlockAuthWithSharedKeyCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableSmartlockAuthWithSharedKeyCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmartlockAuthWithSharedKeyCreate(val *SmartlockAuthWithSharedKeyCreate) *NullableSmartlockAuthWithSharedKeyCreate {
	return &NullableSmartlockAuthWithSharedKeyCreate{value: val, isSet: true}
}

func (v NullableSmartlockAuthWithSharedKeyCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmartlockAuthWithSharedKeyCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


