/*
Nuki API

The Nuki Web Api

API version: 3.9.0
Contact: contact@nuki.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AdvancedApiKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdvancedApiKey{}

// AdvancedApiKey struct for AdvancedApiKey
type AdvancedApiKey struct {
	// The name of the company for which you apply for access
	Name string `json:"name"`
	// The country of the headquarter or the country where you are mainly doing business in
	Country string `json:"country"`
	// Describe the services and/or products you offer to your customers and how your customers would use Nuki devices in their processes
	Description string `json:"description"`
	// The application type
	Type string `json:"type"`
	// The status of the webhook posting automation
	WebhookStatus *string `json:"webhookStatus,omitempty"`
	// A website where we can find more information on the company and its business model
	Url string `json:"url"`
	// An email address where we can contact you for checks on your application
	Email string `json:"email"`
	// The URL where our webhooks should point to
	WebhookUrl string `json:"webhookUrl"`
	// The features to trigger webhooks, for all types except 'ONLY_SECRET'
	WebhookFeatures []string `json:"webhookFeatures"`
	// Whether the advanced API key is restricted
	Restricted bool `json:"restricted"`
	// The client secret, visible if application is approved (status >= 'TESTING')
	Secret string `json:"secret"`
	// The application status
	Status string `json:"status"`
	// The creation date
	CreationDate time.Time `json:"creationDate"`
	// The update date
	UpdateDate time.Time `json:"updateDate"`
}

type _AdvancedApiKey AdvancedApiKey

// NewAdvancedApiKey instantiates a new AdvancedApiKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvancedApiKey(name string, country string, description string, type_ string, url string, email string, webhookUrl string, webhookFeatures []string, restricted bool, secret string, status string, creationDate time.Time, updateDate time.Time) *AdvancedApiKey {
	this := AdvancedApiKey{}
	this.Name = name
	this.Country = country
	this.Description = description
	this.Type = type_
	this.Url = url
	this.Email = email
	this.WebhookUrl = webhookUrl
	this.WebhookFeatures = webhookFeatures
	this.Restricted = restricted
	this.Secret = secret
	this.Status = status
	this.CreationDate = creationDate
	this.UpdateDate = updateDate
	return &this
}

// NewAdvancedApiKeyWithDefaults instantiates a new AdvancedApiKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvancedApiKeyWithDefaults() *AdvancedApiKey {
	this := AdvancedApiKey{}
	return &this
}

// GetName returns the Name field value
func (o *AdvancedApiKey) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKey) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AdvancedApiKey) SetName(v string) {
	o.Name = v
}

// GetCountry returns the Country field value
func (o *AdvancedApiKey) GetCountry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Country
}

// GetCountryOk returns a tuple with the Country field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKey) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Country, true
}

// SetCountry sets field value
func (o *AdvancedApiKey) SetCountry(v string) {
	o.Country = v
}

// GetDescription returns the Description field value
func (o *AdvancedApiKey) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKey) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *AdvancedApiKey) SetDescription(v string) {
	o.Description = v
}

// GetType returns the Type field value
func (o *AdvancedApiKey) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKey) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AdvancedApiKey) SetType(v string) {
	o.Type = v
}

// GetWebhookStatus returns the WebhookStatus field value if set, zero value otherwise.
func (o *AdvancedApiKey) GetWebhookStatus() string {
	if o == nil || IsNil(o.WebhookStatus) {
		var ret string
		return ret
	}
	return *o.WebhookStatus
}

// GetWebhookStatusOk returns a tuple with the WebhookStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedApiKey) GetWebhookStatusOk() (*string, bool) {
	if o == nil || IsNil(o.WebhookStatus) {
		return nil, false
	}
	return o.WebhookStatus, true
}

// HasWebhookStatus returns a boolean if a field has been set.
func (o *AdvancedApiKey) HasWebhookStatus() bool {
	if o != nil && !IsNil(o.WebhookStatus) {
		return true
	}

	return false
}

// SetWebhookStatus gets a reference to the given string and assigns it to the WebhookStatus field.
func (o *AdvancedApiKey) SetWebhookStatus(v string) {
	o.WebhookStatus = &v
}

// GetUrl returns the Url field value
func (o *AdvancedApiKey) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKey) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *AdvancedApiKey) SetUrl(v string) {
	o.Url = v
}

// GetEmail returns the Email field value
func (o *AdvancedApiKey) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKey) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *AdvancedApiKey) SetEmail(v string) {
	o.Email = v
}

// GetWebhookUrl returns the WebhookUrl field value
func (o *AdvancedApiKey) GetWebhookUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WebhookUrl
}

// GetWebhookUrlOk returns a tuple with the WebhookUrl field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKey) GetWebhookUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WebhookUrl, true
}

// SetWebhookUrl sets field value
func (o *AdvancedApiKey) SetWebhookUrl(v string) {
	o.WebhookUrl = v
}

// GetWebhookFeatures returns the WebhookFeatures field value
func (o *AdvancedApiKey) GetWebhookFeatures() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.WebhookFeatures
}

// GetWebhookFeaturesOk returns a tuple with the WebhookFeatures field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKey) GetWebhookFeaturesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WebhookFeatures, true
}

// SetWebhookFeatures sets field value
func (o *AdvancedApiKey) SetWebhookFeatures(v []string) {
	o.WebhookFeatures = v
}

// GetRestricted returns the Restricted field value
func (o *AdvancedApiKey) GetRestricted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Restricted
}

// GetRestrictedOk returns a tuple with the Restricted field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKey) GetRestrictedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Restricted, true
}

// SetRestricted sets field value
func (o *AdvancedApiKey) SetRestricted(v bool) {
	o.Restricted = v
}

// GetSecret returns the Secret field value
func (o *AdvancedApiKey) GetSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Secret
}

// GetSecretOk returns a tuple with the Secret field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKey) GetSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Secret, true
}

// SetSecret sets field value
func (o *AdvancedApiKey) SetSecret(v string) {
	o.Secret = v
}

// GetStatus returns the Status field value
func (o *AdvancedApiKey) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKey) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AdvancedApiKey) SetStatus(v string) {
	o.Status = v
}

// GetCreationDate returns the CreationDate field value
func (o *AdvancedApiKey) GetCreationDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreationDate
}

// GetCreationDateOk returns a tuple with the CreationDate field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKey) GetCreationDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreationDate, true
}

// SetCreationDate sets field value
func (o *AdvancedApiKey) SetCreationDate(v time.Time) {
	o.CreationDate = v
}

// GetUpdateDate returns the UpdateDate field value
func (o *AdvancedApiKey) GetUpdateDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdateDate
}

// GetUpdateDateOk returns a tuple with the UpdateDate field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKey) GetUpdateDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdateDate, true
}

// SetUpdateDate sets field value
func (o *AdvancedApiKey) SetUpdateDate(v time.Time) {
	o.UpdateDate = v
}

func (o AdvancedApiKey) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdvancedApiKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["country"] = o.Country
	toSerialize["description"] = o.Description
	toSerialize["type"] = o.Type
	if !IsNil(o.WebhookStatus) {
		toSerialize["webhookStatus"] = o.WebhookStatus
	}
	toSerialize["url"] = o.Url
	toSerialize["email"] = o.Email
	toSerialize["webhookUrl"] = o.WebhookUrl
	toSerialize["webhookFeatures"] = o.WebhookFeatures
	toSerialize["restricted"] = o.Restricted
	toSerialize["secret"] = o.Secret
	toSerialize["status"] = o.Status
	toSerialize["creationDate"] = o.CreationDate
	toSerialize["updateDate"] = o.UpdateDate
	return toSerialize, nil
}

func (o *AdvancedApiKey) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"country",
		"description",
		"type",
		"url",
		"email",
		"webhookUrl",
		"webhookFeatures",
		"restricted",
		"secret",
		"status",
		"creationDate",
		"updateDate",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdvancedApiKey := _AdvancedApiKey{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdvancedApiKey)

	if err != nil {
		return err
	}

	*o = AdvancedApiKey(varAdvancedApiKey)

	return err
}

type NullableAdvancedApiKey struct {
	value *AdvancedApiKey
	isSet bool
}

func (v NullableAdvancedApiKey) Get() *AdvancedApiKey {
	return v.value
}

func (v *NullableAdvancedApiKey) Set(val *AdvancedApiKey) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvancedApiKey) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvancedApiKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvancedApiKey(val *AdvancedApiKey) *NullableAdvancedApiKey {
	return &NullableAdvancedApiKey{value: val, isSet: true}
}

func (v NullableAdvancedApiKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvancedApiKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


