/*
Nuki API

The Nuki Web Api

API version: 3.10.1
Contact: contact@nuki.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the CacheDirective type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CacheDirective{}

// CacheDirective struct for CacheDirective
type CacheDirective struct {
	Digit *bool `json:"digit,omitempty"`
	Name *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewCacheDirective instantiates a new CacheDirective object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCacheDirective() *CacheDirective {
	this := CacheDirective{}
	return &this
}

// NewCacheDirectiveWithDefaults instantiates a new CacheDirective object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCacheDirectiveWithDefaults() *CacheDirective {
	this := CacheDirective{}
	return &this
}

// GetDigit returns the Digit field value if set, zero value otherwise.
func (o *CacheDirective) GetDigit() bool {
	if o == nil || IsNil(o.Digit) {
		var ret bool
		return ret
	}
	return *o.Digit
}

// GetDigitOk returns a tuple with the Digit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CacheDirective) GetDigitOk() (*bool, bool) {
	if o == nil || IsNil(o.Digit) {
		return nil, false
	}
	return o.Digit, true
}

// HasDigit returns a boolean if a field has been set.
func (o *CacheDirective) HasDigit() bool {
	if o != nil && !IsNil(o.Digit) {
		return true
	}

	return false
}

// SetDigit gets a reference to the given bool and assigns it to the Digit field.
func (o *CacheDirective) SetDigit(v bool) {
	o.Digit = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CacheDirective) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CacheDirective) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CacheDirective) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CacheDirective) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CacheDirective) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CacheDirective) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CacheDirective) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *CacheDirective) SetValue(v string) {
	o.Value = &v
}

func (o CacheDirective) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CacheDirective) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Digit) {
		toSerialize["digit"] = o.Digit
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableCacheDirective struct {
	value *CacheDirective
	isSet bool
}

func (v NullableCacheDirective) Get() *CacheDirective {
	return v.value
}

func (v *NullableCacheDirective) Set(val *CacheDirective) {
	v.value = val
	v.isSet = true
}

func (v NullableCacheDirective) IsSet() bool {
	return v.isSet
}

func (v *NullableCacheDirective) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCacheDirective(val *CacheDirective) *NullableCacheDirective {
	return &NullableCacheDirective{value: val, isSet: true}
}

func (v NullableCacheDirective) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCacheDirective) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


