/*
Nuki API

The Nuki Web Api

API version: 3.9.0
Contact: contact@nuki.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AdvancedApiKeyUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdvancedApiKeyUpdate{}

// AdvancedApiKeyUpdate struct for AdvancedApiKeyUpdate
type AdvancedApiKeyUpdate struct {
	// The URL where our webhooks should point to
	WebhookUrl string `json:"webhookUrl"`
	// The features to trigger webhooks, for all types except 'ONLY_SECRET'
	WebhookFeatures []string `json:"webhookFeatures"`
}

type _AdvancedApiKeyUpdate AdvancedApiKeyUpdate

// NewAdvancedApiKeyUpdate instantiates a new AdvancedApiKeyUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvancedApiKeyUpdate(webhookUrl string, webhookFeatures []string) *AdvancedApiKeyUpdate {
	this := AdvancedApiKeyUpdate{}
	this.WebhookUrl = webhookUrl
	this.WebhookFeatures = webhookFeatures
	return &this
}

// NewAdvancedApiKeyUpdateWithDefaults instantiates a new AdvancedApiKeyUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvancedApiKeyUpdateWithDefaults() *AdvancedApiKeyUpdate {
	this := AdvancedApiKeyUpdate{}
	return &this
}

// GetWebhookUrl returns the WebhookUrl field value
func (o *AdvancedApiKeyUpdate) GetWebhookUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WebhookUrl
}

// GetWebhookUrlOk returns a tuple with the WebhookUrl field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKeyUpdate) GetWebhookUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WebhookUrl, true
}

// SetWebhookUrl sets field value
func (o *AdvancedApiKeyUpdate) SetWebhookUrl(v string) {
	o.WebhookUrl = v
}

// GetWebhookFeatures returns the WebhookFeatures field value
func (o *AdvancedApiKeyUpdate) GetWebhookFeatures() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.WebhookFeatures
}

// GetWebhookFeaturesOk returns a tuple with the WebhookFeatures field value
// and a boolean to check if the value has been set.
func (o *AdvancedApiKeyUpdate) GetWebhookFeaturesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WebhookFeatures, true
}

// SetWebhookFeatures sets field value
func (o *AdvancedApiKeyUpdate) SetWebhookFeatures(v []string) {
	o.WebhookFeatures = v
}

func (o AdvancedApiKeyUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdvancedApiKeyUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["webhookUrl"] = o.WebhookUrl
	toSerialize["webhookFeatures"] = o.WebhookFeatures
	return toSerialize, nil
}

func (o *AdvancedApiKeyUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"webhookUrl",
		"webhookFeatures",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdvancedApiKeyUpdate := _AdvancedApiKeyUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdvancedApiKeyUpdate)

	if err != nil {
		return err
	}

	*o = AdvancedApiKeyUpdate(varAdvancedApiKeyUpdate)

	return err
}

type NullableAdvancedApiKeyUpdate struct {
	value *AdvancedApiKeyUpdate
	isSet bool
}

func (v NullableAdvancedApiKeyUpdate) Get() *AdvancedApiKeyUpdate {
	return v.value
}

func (v *NullableAdvancedApiKeyUpdate) Set(val *AdvancedApiKeyUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvancedApiKeyUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvancedApiKeyUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvancedApiKeyUpdate(val *AdvancedApiKeyUpdate) *NullableAdvancedApiKeyUpdate {
	return &NullableAdvancedApiKeyUpdate{value: val, isSet: true}
}

func (v NullableAdvancedApiKeyUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvancedApiKeyUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


